walk(document.body || document.documentElement);
observeDocument();

function walk(node) 
{
	// I stole this function from here:
	// http://is.gd/mwZp7E
	
	var child, next;
	
	var tagName = node.tagName ? node.tagName.toLowerCase() : "";
	if (
		tagName == 'input' ||
		tagName == 'textarea' ||
		tagName == 'script' ||
		tagName == 'style' ||
		tagName == 'noscript'
	) {
		return;
	}
	if (node.classList && node.classList.contains('ace_editor')) {
		return;
	}

	switch ( node.nodeType )  
	{
		case 1:  // Element
		case 9:  // Document
		case 11: // Document fragment
			child = node.firstChild;
			while ( child ) 
			{
				next = child.nextSibling;
				walk(child);
				child = next;
			}
			break;

		case 3: // Text node
			handleText(node);
			break;
	}
}

function observeDocument() {
	var observer = new MutationObserver(function(mutations) {
		mutations.forEach(function(mutation) {
			for (var i = 0; i < mutation.addedNodes.length; i++) {
				walk(mutation.addedNodes[i]);
			}

			if (mutation.type === 'characterData') {
				handleText(mutation.target);
			}
		});
	});

	observer.observe(document.documentElement, {
		childList: true,
		subtree: true,
		characterData: true
	});
}

function handleText(textNode) 
{
	var v = textNode.nodeValue;
	var replacements = [
		[/\bArtificial Intelligence\b/g, "Arse"],
		[/\bartificial intelligence\b/g, "arse"],
		[/\bThinking Systems\b/g, "Arse Systems"],
		[/\bthinking systems\b/g, "arse systems"],
		[/\bReasoning Systems\b/g, "Arse Systems"],
		[/\breasoning systems\b/g, "arse systems"],
		[/\bNatural Language Processing\b/g, "Arse Processing"],
		[/\bnatural language processing\b/g, "arse processing"],
		[/\bPrompt Engineering\b/g, "Arse Wrangling"],
		[/\bprompt engineering\b/g, "arse wrangling"],
		[/\bAI-assisted writing\b/g, "arse-assisted writing"],
		[/\bAI assisted writing\b/g, "arse assisted writing"],
		[/\bLLM-assisted writing\b/g, "arse-assisted writing"],
		[/\bLLM assisted writing\b/g, "arse assisted writing"],
		[/\bLLM prose\b/g, "arse prose"],
		[/\bLLM judge\b/g, "arse judge"],
		[/\bMulti-agent workflows\b/g, "Multi-arse workflows"],
		[/\bmulti-agent workflows\b/g, "multi-arse workflows"],
		[/\bMulti-agent workflow\b/g, "Multi-arse workflow"],
		[/\bmulti-agent workflow\b/g, "multi-arse workflow"],
		[/\bMulti-agent\b/g, "Multi-arse"],
		[/\bmulti-agent\b/g, "multi-arse"],
		[/\bLead agent\b/g, "Lead arse"],
		[/\blead agent\b/g, "lead arse"],
		[/\bSub-agent\b/g, "Sub-arse"],
		[/\bsub-agent\b/g, "sub-arse"],
		[/\bAgent coordination\b/g, "Arse coordination"],
		[/\bagent coordination\b/g, "arse coordination"],
		[/\bAgent orchestration\b/g, "Arse orchestration"],
		[/\bagent orchestration\b/g, "arse orchestration"],
		[/\bAgentic\b/g, "Arse-driven"],
		[/\bagentic\b/g, "arse-driven"],
		[/\bCoding Agents\b/g, "Arse Assistants"],
		[/\bcoding agents\b/g, "arse assistants"],
		[/\bCoding Agent\b/g, "Arse Assistant"],
		[/\bcoding agent\b/g, "arse assistant"],
		[/\bOn-device AI\b/g, "On-device arse"],
		[/\bon-device AI\b/g, "on-device arse"],
		[/\bAI-powered\b/g, "arse-powered"],
		[/\bAI powered\b/g, "arse powered"],
		[/\bPowered by AI\b/g, "Powered by arse"],
		[/\bpowered by AI\b/g, "powered by arse"],
		[/\bBuilt with AI\b/g, "Built with arse"],
		[/\bbuilt with AI\b/g, "built with arse"],
		[/\bUsing AI\b/g, "Using arse"],
		[/\busing AI\b/g, "using arse"],
		[/\bUses AI\b/g, "Uses arse"],
		[/\buses AI\b/g, "uses arse"],
		[/\bUse AI\b/g, "Use arse"],
		[/\buse AI\b/g, "use arse"],
		[/\bGenerated by AI\b/g, "Generated by arse"],
		[/\bgenerated by AI\b/g, "generated by arse"],
		[/\bAI-generated\b/g, "arse-generated"],
		[/\bAI assistant\b/g, "arse assistant"],
		[/\bAI assistants\b/g, "arse assistants"],
		[/\bAI tool\b/g, "arse tool"],
		[/\bAI tools\b/g, "arse tools"],
		[/\bAI feature\b/g, "arse feature"],
		[/\bAI features\b/g, "arse features"],
		[/\bAI company\b/g, "arse company"],
		[/\bAI companies\b/g, "arse companies"],
		[/\bAI startup\b/g, "arse startup"],
		[/\bAI startups\b/g, "arse startups"],
		[/\bAI product\b/g, "arse product"],
		[/\bAI products\b/g, "arse products"],
		[/\bAI content\b/g, "arse content"],
		[/\bAI account\b/g, "arse account"],
		[/\bAI accounts\b/g, "arse accounts"],
		[/\bAI model\b/g, "arse model"],
		[/\bAI models\b/g, "arse models"],
		[/\bAI provider\b/g, "arse provider"],
		[/\bAI providers\b/g, "arse providers"],
		[/\bAI training\b/g, "arse training"],
		[/\bAI user\b/g, "arse user"],
		[/\bAI users\b/g, "arse users"],
		[/\bAI debate\b/g, "arse debate"],
		[/\bAI arms race\b/g, "arse arms race"],
		[/\bAI era\b/g, "arse era"],
		[/\bAI slop\b/g, "arse slop"],
		[/\bGenAI\b/g, "arse"],
		[/\bgenAI\b/g, "arse"],
		[/\bGen AI\b/g, "arse"],
		[/\bgen AI\b/g, "arse"],
		[/A\.I\./g, "arse"],
		[/\bAIs\b/g, "arses"],
		[/\bAI's\b/g, "arse's"],
		[/\bAI’s\b/g, "arse’s"],
		[/\bAI\b/g, "arse"],
		[/\bLLMs\b/g, "arses"],
		[/\bLLM\b/g, "arse"]
	];

	for (var i = 0; i < replacements.length; i++) {
		v = v.replace(replacements[i][0], replacements[i][1]);
	}

	// Grammar cleanups after bare "AI" -> "arse" replacements.
	v = v
		.replace(/\ba arse\b/g, "an arse")
		.replace(/\bA arse\b/g, "An arse")
		.replace(/\ba arse-/g, "an arse-")
		.replace(/\bA arse-/g, "An arse-")
		.replace(/\ba arse's\b/g, "an arse's")
		.replace(/\bA arse's\b/g, "An arse's")
		.replace(/\ba arse’s\b/g, "an arse’s")
		.replace(/\bA arse’s\b/g, "An arse’s");
	
	textNode.nodeValue = v;
}


